extends:
  - spectral:oas

rules:
  duplicated-entry-in-enum:
    given: "$..[?(@ && @property !== 'properties' && @.enum && @.enum.constructor.name === 'Array')]"
    then:
      field: enum
      function: schema
      functionOptions:
        schema:
          type: array
          uniqueItems: true
  gam-operation-operation-id:
    given: $.paths[*][*]
    then:
      field: operationId
      function: truthy
    severity: error
  gam-operation-summary:
    given: $.paths[*][*]
    then:
      field: summary
      function: truthy
    severity: error
  gam-operation-description:
    given: $.paths[*][*]
    then:
      field: description
      function: truthy
    severity: error
  gam-operation-tags:
    given: $.paths[*][*]
    then:
      field: tags
      function: truthy
    severity: error
