spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start-only
spring.flyway.locations=classpath:db/migration,classpath:db/dev-migration

springdoc.swagger-ui.supported-submit-methods=get,post,patch,delete

jwt.secret-key=${JWT_SECRET_KEY}

app.auth.cookie.secure=false
GAM_PUBLIC_ORIGIN=http://localhost:3000
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
