spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start-only

jwt.secret-key=${JWT_SECRET_KEY}

app.auth.cookie.secure=false
cors.allowed-origins=http://localhost:3000

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
