spring.application.name=gam-api
spring.application.version=${APP_VERSION:0.0.1-SNAPSHOT}
spring.docker.compose.enabled=false
spring.jackson.deserialization.fail-on-unknown-properties=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.api-docs.path=/api/openapi.json
springdoc.api-docs.version=OPENAPI_3_1
springdoc.swagger-ui.path=/api/docs
springdoc.swagger-ui.supported-submit-methods=

# 1 hour
jwt.expiration-ms=3600000 

# 7 days
jwt.refresh-expiration-ms=604800000
