package br.org.gam.api.shared.activitylog;

public enum ActivityTargetType {
    ACCOUNT,
    ACCOUNT_ROLE_ASSIGNMENT,
    EVENT,
    GAM_LOCATION,
    MEMBER,
    MEMBERSHIP_SOLICITATION,
    ORATORIO,
    ORATORIANO,
    ORATORIANO_ATTENDANCE,
    ORATORIANO_FORM,
    ORATORIANO_FORM_PRINT_SNAPSHOT,
    PRESENCE,
    ROLE,
    PERMISSION,
    ROLE_PERMISSION_ASSIGNMENT
}
