package br.org.gam.api.shared.activitylog;

public enum ActivityAction {
    ACCOUNT_ROLE_ADDED,
    ACCOUNT_ROLE_REMOVED,
    EVENT_CREATED,
    MEMBER_REGISTERED,
    MEMBER_ACTIVATED,
    MEMBER_DEACTIVATED,
    MEMBERSHIP_SOLICITATION_SUBMITTED,
    MEMBERSHIP_SOLICITATION_APPROVED,
    MEMBERSHIP_SOLICITATION_REJECTED,
    MISSA_CREATED,
    ORATORIO_CREATED,
    PRESENCE_REGISTERED,
    GAM_LOCATION_CREATED,
    GAM_LOCATION_UPDATED,
    GAM_LOCATION_REMOVED,
    DEVELOPER_RESTORE_EXECUTED,
    DEVELOPER_HARD_DELETE_EXECUTED,
    DEVELOPER_VIEWED_SOFT_DELETED_RECORDS
}
