package br.org.gam.api.shared.activitylog;

public enum ActivityTargetType {
    ACCOUNT_ROLE,
    EVENT,
    MEMBER,
    MEMBERSHIP_SOLICITATION,
    MISSA,
    ORATORIO,
    ORATORIANO,
    ORATORIANO_ATTENDANCE,
    ORATORIANO_FORM,
    ORATORIANO_FORM_PRINT_SNAPSHOT,
    PRESENCE,
    GAM_LOCATION,
    MAINTENANCE_RECORD
}
